# Form implementation generated from reading ui file '/home/sourabh/Work/WorkTask/.qt_for_python/uic/comtrial_previous.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontal_input_container = QtWidgets.QHBoxLayout()
        self.horizontal_input_container.setObjectName("horizontal_input_container")
        self.port_box = QtWidgets.QHBoxLayout()
        self.port_box.setObjectName("port_box")
        self.port_label = QtWidgets.QLabel(self.centralwidget)
        self.port_label.setObjectName("port_label")
        self.port_box.addWidget(self.port_label)
        self.port_input = QtWidgets.QLineEdit(self.centralwidget)
        self.port_input.setObjectName("port_input")
        self.port_box.addWidget(self.port_input)
        self.horizontal_input_container.addLayout(self.port_box)
        self.baudrate_box = QtWidgets.QHBoxLayout()
        self.baudrate_box.setObjectName("baudrate_box")
        self.baudrate_label = QtWidgets.QLabel(self.centralwidget)
        self.baudrate_label.setObjectName("baudrate_label")
        self.baudrate_box.addWidget(self.baudrate_label)
        self.baudrate_input = QtWidgets.QLineEdit(self.centralwidget)
        self.baudrate_input.setObjectName("baudrate_input")
        self.baudrate_box.addWidget(self.baudrate_input)
        self.horizontal_input_container.addLayout(self.baudrate_box)
        self.parity_box = QtWidgets.QHBoxLayout()
        self.parity_box.setObjectName("parity_box")
        self.parity_label = QtWidgets.QLabel(self.centralwidget)
        self.parity_label.setObjectName("parity_label")
        self.parity_box.addWidget(self.parity_label)
        self.parity_input = QtWidgets.QLineEdit(self.centralwidget)
        self.parity_input.setObjectName("parity_input")
        self.parity_box.addWidget(self.parity_input)
        self.horizontal_input_container.addLayout(self.parity_box)
        self.verticalLayout.addLayout(self.horizontal_input_container)
        self.enter_button = QtWidgets.QPushButton(self.centralwidget)
        self.enter_button.setObjectName("enter_button")
        self.verticalLayout.addWidget(self.enter_button, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.port_label.setText(_translate("MainWindow", "Port:"))
        self.baudrate_label.setText(_translate("MainWindow", "Baudrate"))
        self.parity_label.setText(_translate("MainWindow", "Parity"))
        self.enter_button.setText(_translate("MainWindow", "Enter"))
